CREATE TABLE T_GS_USER(
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_email VARCHAR(100) UNIQUE,
    user_password VARCHAR(100),
    user_status VARCHAR(100)
);

CREATE TABLE T_GS_PROFILE(
    profile_cpf VARCHAR(20) PRIMARY KEY,
    profile_birthdate DATE,
    profile_username  VARCHAR(30)UNIQUE,
    profile_score INTEGER,
    profile_name VARCHAR(100),
    user_id_fk INTEGER,
    FOREIGN KEY (user_id_fk) REFERENCES T_GS_USER(user_id)
);

CREATE TABLE T_GS_TELEPHONE(
    telephone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telephone_ddd VARCHAR(10),
    telephone_number VARCHAR(25),
    profile_cpf_fk VARCHAR(20),
    FOREIGN KEY (profile_cpf_fk) REFERENCES T_GS_PROFILE(profile_cpf)
);

CREATE TABLE T_GS_ADDRESS(
    address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address_street VARCHAR(100),
    address_number VARCHAR(10),
    address_add_info VARCHAR(100),
    address_city VARCHAR(100),
    address_state VARCHAR (100),
    address_zipcode VARCHAR (100),
    profile_cpf_fk VARCHAR(20),
    FOREIGN KEY (profile_cpf_fk) REFERENCES T_GS_PROFILE(profile_cpf)
);

CREATE TABLE T_GS_USAGE(
    usage_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pickup_datetime DATE,
    return_datetime DATE,
    usage_duration FLOAT,
    usage_score INTEGER,
    profile_cpf_fk VARCHAR(20),
    FOREIGN KEY (profile_cpf_fk) REFERENCES T_GS_PROFILE(profile_cpf)
);

CREATE TABLE T_GS_PAYMENT(
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_amount FLOAT,
    payment_type VARCHAR(20),
    usage_id_fk INTEGER,
    FOREIGN KEY (usage_id_fk) REFERENCES T_GS_USAGE(usage_id)
);