CREATE TABLE T_GS_USER(
                          user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_email  varchar(100) UNIQUE,
                          user_password varchar(100),
                          user_status varchar(100)
);

CREATE TABLE T_GS_TELEPHONE(
                               telephone_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               telephone_ddd varchar(10),
                               telephone_number varchar(25)
);

CREATE TABLE T_GS_ADDRESS(
                             address_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             address_street varchar(100),
                             address_number varchar(10),
                             address_add_info varchar(100),
                             address_city varchar(100),
                             address_state varchar (100),
                             address_zipcode varchar (100)
);

CREATE TABLE T_GS_PAYMENT(
                             payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             payment_amount FLOAT,
                             payment_type varchar(20)
);

CREATE TABLE T_GS_PROFILE(
                             profile_cpf varchar(20) PRIMARY KEY,
                             profile_birthdate DATE,
                             profile_username  varchar(30)UNIQUE,
                             profile_score INTEGER,
                             profile_name varchar(100),
                             user_id_fk INTEGER,
                             address_id_fk INTEGER,
                             telephone_id_fk INTEGER,
                             FOREIGN KEY (user_id_fk) REFERENCES T_GS_USER(user_id),
                             FOREIGN KEY (address_id_fk) REFERENCES T_GS_Address(address_id),
                             FOREIGN KEY (telephone_id_fk) REFERENCES T_GS_TELEPHONE(telephone_id)

);


CREATE TABLE T_GS_USAGE(
                           usage_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           pickup_datetime DATE,
                           return_datetime DATE,
                           usage_duration FLOAT,
                           usage_score INTEGER,
                           profile_cpf_fk varchar(20),
                           payment_id_fk integer,
                           FOREIGN KEY (profile_cpf_fk) REFERENCES T_GS_PROFILE(profile_cpf),
                           FOREIGN KEY (payment_id_fk) REFERENCES T_GS_PAYMENT(payment_id)

);